cc_library(
    name = "hello_lib",
    srcs = ["hello_lib.cpp"],
    hdrs = ["hello_lib.hpp"],
    deps = [
        "@fmt//:fmt",  # 引入 fmt 库
    ],
    visibility = ["//visibility:public"],  # 允许 main 包访问
)
