name: CI (Bazel)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 设置 Bazel 环境
      - name: Setup Bazel environment
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
      # 3️⃣ 构建项目
      - name: Build (Debug)
        run: |
          bazel build --config=debug //...
      - name: Build (Release)
        run: |
          bazel build --config=release //...

      # 4️⃣ 运行测试
      - name: Run tests
        run: |
          bazel test --config=debug //tests:all

